### PR TITLE
Haskell implementation

### PR DESCRIPTION
**Pull request by mroman42**
First fully-working Haskell implementation of the benchmarks. Uses a `Mutable.Vector` as the main data structure and an imperative-like style of programming. This implementation is very slow yet, optimizations should be added to achieve a reasonable timing.

### CODE REVIEW

**Comment by JJ** [comment]
Maybe it would be faster with immutable vectors?

**Comment by mroman42** [comment]
Yes, almost surely. I started using mutable vectors with unsafe monadic operations because I thought these should be faster, but it seems they are very slow. Now I want to try using:
- Data.Vector.Inmutable
- Data.Sequence
- And the [persistent-vectors](http://stackoverflow.com/a/32931311/2552681) package

I will try to find the fastest between them. I would appreciate any other ideas about the data structures.

**Comment by mroman42** [comment]
I'm trying to implement this in M42/2015-ea-languages. I will submit a new pull request when I finish. Maybe a more accurate time measurement system would be needed.

**Comment by JJ** [comment]
Please go to https://github.com/JJ/2016-ea-languages-wcci

And remember to add yourself to the authors.

**Comment by JJ** [comment]
And please do it soon. I need to run everything again in a computer that I
will have available only until tomorrow evening.

**Pull request merged**
